# This is a basic workflow to help you get started with Actions

name: Build & test

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install yarn
        run: npm install -g corepack

      - name: Install dependencies
        run: yarn install

      - name: Generate build artifact
        run: CI=false yarn run build

      - name: Run tests
        run: yarn test -- --coverage
