# This is a basic workflow to help you get started with Actions

name: Build & test

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yarn
        run: npm install -g corepack

      - name: Install dependencies
        run: yarn install

      - name: Generate build artifact
        run: CI=true yarn run build

      - name: Run tests
        run: yarn test --ci --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
